### ISSUE TITLE
Good mod but I can't download any skin, I don't know why, can you help me fix it

### ISSUE THREAD

**Issue by mengzhu3261** [Wyvest/skin-downloader#1]
Good mod but I can't download any skin, I don't know why, can you help me fix it

**Comment by Wyvest** [comment]
<img width="632" alt="Screenshot 2023-11-14 at 7 49 02 AM" src="https://github.com/Wyvest/skin-downloader/assets/45589059/50dab70c-e998-4878-ac5b-aa565084e34a">
did you follow this? it should work. please give more info

**Comment by mengzhu3261** [comment]
> <img alt="Screenshot 2023-11-14 at 7 49 02 AM" width="632" src="https://user-images.githubusercontent.com/45589059/282779158-50dab70c-e998-4878-ac5b-aa565084e34a.png">你跟着这个吗？它应该起作用。请提供更多信息
Can I add your dis? I'll send you the crash log

**Comment by Wyvest** [comment]
> > <img alt="Screenshot 2023-11-14 at 7 49 02 AM" width="632" src="https://user-images.githubusercontent.com/45589059/282779158-50dab70c-e998-4878-ac5b-aa565084e34a.png">你跟着这个吗？它应该起作用。请提供更多信息
> > Can I add your dis? I'll send you the crash log

join discord.gg/polyfrost
